export const SET_LOADING = "SET_LOADING";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
