export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const GET_INSTRUCTOR_FAIL = "GET_INSTRUCTOR_FAIL";
export const GET_INSTRUCTOR_SUCCESS = "GET_INSTRUCTOR_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_ERROR = "FORGOT_PASS_ERROR";
export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
export const RESET_PASS_ERROR = "RESET_PASS_ERROR";

export const PAYEMENT_SUCESS = "PAYEMENT_SUCESS";
export const PAYEMENT_FAIL = "PAYEMENT_FAIL";

export const STRIPESTATUS_SUCCESS = "STRIPESTATUS_SUCCESS";
export const STRIPESTATUS_FAIL = "STRIPESTATUS_FAIL";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOG_OUT = "LOG_OUT";

export const CREATECOURSE_SUCCESS = "CREATECOURSE_SUCCESS";
export const CREATECOURSE_FAIL = "CREATECOURSE_FAIL";

export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAIL = "GET_COURSES_FAIL";

export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAIL = "GET_COURSE_FAIL";

export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";

export const DELETECOURSE_SUCCESS = "DELETECOURSE_SUCCESS";
export const DELETECOURSE_FAIL = "DELETECOURSE_FAIL";

//Loadings
export const SET_LOADING_USER = "SET_LOADING_USER";
export const SET_LOADING_INSTRUCTOR = "SET_LOADING_INSTRUCTOR";
export const SET_LOADING_PAYMENT = "SET_LOADING_PAYMENT";
export const SET_LOADING_REGISTER = "SET_LOADING_REGISTER";
export const SET_LOADING_CREATECOURSE = "SET_LOADING_CREATECOURSE";
